# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
   
      - image: python:2.7.14-alpine3.7

    working_directory: ~/python-sample

    steps:
      - checkout

      - run: mkdir test-reports

      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}

      - run:
          name: Install requirements
          command: |
            pip install lxml
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: name
          command: |
            python test.py
            
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
